/**
 *
 * $Id$
 */
package emfta.validation;

import emfta.Event;
import emfta.Gate;
import emfta.GateType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link emfta.Gate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GateValidator {
	boolean validate();

	boolean validateType(GateType value);
	boolean validateGates(EList<Gate> value);
	boolean validateEvents(EList<Event> value);
}
